// Auto-generated contract deployment data
// This file is generated by sync-contracts.py - DO NOT EDIT MANUALLY
// Generated on: 2025-08-24T09:57:31.116222

export const contractsData = {
  networks: {
      97: {
          name: "bsc-testnet",
          chainId: 97,
          type: "testnet" as const,
          explorer: "https://testnet.bscscan.com",
          contracts: {
              DepositContract: "0x575b07E3cC36eEeC6B94ac5D09f6285ecE2a66dd",
              Gateway: "0x0c487a766110c85d301d96e33579c5b317fa4995",
            },
          tokens: {
              BNB: "0x0000000000000000000000000000000000000000",
              USDC: "0x64544969ed7EBf5f083679233325356EbE738930",
            },
        },
      7001: {
          name: "zeta-testnet",
          chainId: 7001,
          type: "testnet" as const,
          rpc: "https://zetachain-athens-evm.blockpi.network/v1/rpc/public",
          explorer: "https://athens.explorer.zetachain.com",
          contracts: {
              SimpleLendingProtocol: "0xcec503D661A9C56AFa91AcDB4D7A2BFe411a5416",
              UniversalLendingProtocol: "0x5bD0EeF491fB64dc0e0729431b43911947Ed0ed2",
              PriceOracle: "0x0000000000000000000000000000000000000000",
              MockPriceOracle: "0x3611ec20Ab7904E914E1Dbb47F536fE8c54ddC8E",
              Universal: "0x0000000000000000000000000000000000000000",
            },
          tokens: {
              "ETH.ARBI": "0x1de70f3e971B62A0707dA18100392af14f7fB677",
              "USDC.ARBI": "0x4bC32034caCcc9B7e02536945eDbC286bACbA073",
              "ETH.ETH": "0x05BA149A7bd6dC1F937fA9046A9e05C05f3b18b0",
              "USDC.ETH": "0xcC683A782f4B30c138787CB5576a86AF66fdc31d",
              ZETA: "0x0000000000000000000000000000000000000000",
              "USDC.POL": "0xe573a6e11f8506620F123DBF930222163D46BCB6",
              "POL.POL": "0x777915D031d1e8144c90D025C594b3b8Bf07a08d",
              "USDC.BSC": "0x7c8dDa80bbBE1254a7aACf3219EBe1481c6E01d7",
              "BNB.BSC": "0xd97B1de3619ed2c6BEb3860147E30cA8A7dC9891",
              "ETH.BASE": "0x236b0DE675cC8F46AE186897fCCeFe3370C9eDeD",
              "USDC.BASE": "0xd0eFed75622e7AA4555EE44F296dA3744E3ceE19",
              "SOL.SOL": "0xADF73ebA3Ebaa7254E859549A44c74eF7cff7501",
              "USDC.SOL": "0xD10932EB3616a937bd4a2652c87E9FeBbAce53e5",
            },
        },
      80002: {
          name: "polygon-amoy",
          chainId: 80002,
          type: "testnet" as const,
          explorer: "https://amoy.polygonscan.com",
          contracts: {
              DepositContract: "0x55E1Bd43F67BaB1E176E2A65608C151bC0d8F148",
              Gateway: "0x0c487a766110c85d301d96e33579c5b317fa4995",
            },
          tokens: {
              POL: "0x0000000000000000000000000000000000000000",
              USDC: "0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582",
            },
        },
      84532: {
          name: "base-sepolia",
          chainId: 84532,
          type: "testnet" as const,
          explorer: "https://sepolia.basescan.org",
          contracts: {
              DepositContract: "0x701B48270c8d2F2c84746be7CeB003A256E61145",
              Gateway: "0x0c487a766110c85d301d96e33579c5b317fa4995",
            },
          tokens: {
              ETH: "0x0000000000000000000000000000000000000000",
              USDC: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
            },
        },
      421614: {
          name: "arbitrum-sepolia",
          chainId: 421614,
          type: "testnet" as const,
          explorer: "https://sepolia.arbiscan.io",
          contracts: {
              DepositContract: "0x589521F58dC8FBf99499D7Eb8B31cb1d9d228a0E",
              Gateway: "0x0dA86Dc3F9B71F84a0E97B0e2291e50B7a5df10f",
            },
          tokens: {
              ETH: "0x0000000000000000000000000000000000000000",
              USDC: "0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d",
            },
        },
      11155111: {
          name: "ethereum-sepolia",
          chainId: 11155111,
          type: "testnet" as const,
          explorer: "https://sepolia.etherscan.io",
          contracts: {
              DepositContract: "0x07058282910F6a7aDC2fe307E92DA56Cd39F183D",
              Gateway: "0x0c487a766110c85d301d96e33579c5b317fa4995",
            },
          tokens: {
              ETH: "0x0000000000000000000000000000000000000000",
              USDC: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238",
            },
        },
    },
  deployments: {
      lastUpdated: "2025-08-24T01:45:25.271Z",
      deployer: "0xe1C5Bf97A7Ffb50988DeF972E1E242072298a59C",
    },
};
